spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 65068600
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
#    user: postgres
#    password: 65068600
#    schemas:
#      - axon-usage
    enabled: true
#    locations: classpath:migrations
    baseline-on-migrate: true

axon:
  axonserver:
    enabled: false